### ISSUE TITLE
[BUG]: Redis is weirdly slow when using .all_pks()

### ISSUE THREAD

**Issue by XuhuiZhou** [sotopia-lab/sotopia#158] opened 2024-07-26 23:18 UTC
### Description of the bug

Not sure why this is the case, but whenever the redis server is hosted at a different place (us east vs us west) there's this significant slow. Especially when using `.all_pks()`

This behavior is kind of buggy since it's losing the purpose of using redis if such a delay exist

### Steps To Reproduce

1. config a server that's not in CMU (ideally somewhere us west)
2. `python examples/minimalist_demo.py`

**Comment by ProKil** [comment] 2024-07-27 01:33
This is not a function managed by the sotopia package.

Can you report it to the redis_om package?

**Comment by XuhuiZhou** [comment] 2024-07-27 01:41
Right, just curious whether we can fix this internally

**Comment by ProKil** [comment] 2024-07-27 01:47
all_pks uses [`scan_iter`](https://github.com/redis/redis-om-python/blob/b20e887ccf2b4f80908d5c04bc0eee3641ddcdf2/aredis_om/model/model.py#L1715), which is memory efficient, but not time efficient:

As discussed in
https://github.com/redis/redis-py/issues/1102

**Comment by ProKil** [comment] 2024-07-27 01:54
I would suggest always set up redis close to you. It doesn't make sense to set up redis on the different end of continent across 3 time zones. 

If you have to do `all_pks` across continent very often, you can use `keys` which is more memory intensive but cpu efficient. But there is a reason why redis om uses scan_iter instead of keys...

**Comment by XuhuiZhou** [comment] 2024-07-27 02:01
I thought one big advantage of redis is people can collaborate in a central
place

**Comment by ProKil** [comment] 2024-07-27 02:22
I don't see any performance bug in this right now, and the methods are doing what they claim to do. 

The latency of the network is limited by its physical property, so I don't see any way to avoid this.

**Comment by ProKil** [comment] 2024-07-27 02:23
Is there any usage where you have to do `all_pks()` a lot of times? I think it is mainly an one-off thing, and you should avoid use it in a loop. You should use `find()` to avoid downloading data that you may not need.

**Comment by ProKil** [comment] 2024-07-27 03:54
Raising #159 to eliminate all `all_pks` from sotopia core library. Closing this since this is not a bug. I would still advice against deploying redis in a remote region.

**Closed by ProKil** 2024-07-27 03:54 UTC
Labels: bug
